CONFIGURATION:
  urlfortelemetry: http://192.168.1.100:25555/api/ets2/telemetry  # the telemetry server's access url
  arduinoport: COM3                                               # the arduino board's port (check arduino IDE)
  debugmode: False                                                # return debug lines (True/False) (False by default)

VEHICLE:
  autoretarder: True                                              # set to True if the automatic retarder is enabled in-game (True/False) (True by default)
  checkelectrical: True                                           # set to False if you don't want the software to check for electricity when lighting up the indicator lights (used for battery voltage warning and handbrake) (True by default) (True/False)
  independentlights: False                                        # set to True if you want to check the external lights independently of the truck electrical state (True/False) (False by default)